name: build

on:
  pull_request_target:
    branches:
      - main
    paths:
      - README.md

jobs:
  plugin-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - uses: actions/setup-node@v2
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');

    permissions:
      contents: read
      issues: write
      pull-requests: write
