name: build

on:
  pull_request_target:
    branches:
      - main
    paths:
      - README.md

jobs:
  plugin-validation:
    runs-on: ubuntu-latest
      - name: Checkout code
        uses: actions/checkout@v4
        id: checkout_code

      - name: hello
        id: build
        run: |
          echo helllooooo
    permissions:
      contents: read
      issues: write
      pull-requests: write
