name: build

on:
  pull_request_target:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        id: checkout_code

      - name: x
        run: |
          echo hellooooo
